
#!/usr/bin/env python3
import os
import glob
import xml.etree.ElementTree as ET
from html import escape
from collections import defaultdict

REPORT_DIR = os.path.join('target', 'site')
SRC_DIR = os.path.join('target', 'surefire-reports')
OUT_FILE = os.path.join(REPORT_DIR, 'surefire-report.html')

os.makedirs(REPORT_DIR, exist_ok=True)

tests_by_class = defaultdict(list)
summary = {'tests':0,'failures':0,'errors':0,'skipped':0,'time':0.0}

for path in glob.glob(os.path.join(SRC_DIR, 'TEST-*.xml')):
    try:
        tree = ET.parse(path)
        root = tree.getroot()
        t = int(root.attrib.get('tests', '0'))
        f = int(root.attrib.get('failures', '0'))
        e = int(root.attrib.get('errors', '0'))
        s = int(root.attrib.get('skipped', '0'))
        time = float(root.attrib.get('time', '0'))
        summary['tests'] += t
        summary['failures'] += f
        summary['errors'] += e
        summary['skipped'] += s
        summary['time'] += time

        for case in root.findall('.//testcase'):
            name = case.attrib.get('name')
            classname = case.attrib.get('classname') or 'Unknown'
            time = case.attrib.get('time', '0')
            status = 'passed'
            msg = ''
            if case.find('failure') is not None:
                status = 'failure'
                msg = case.find('failure').attrib.get('message','') or (case.find('failure').text or '')
            elif case.find('error') is not None:
                status = 'error'
                msg = case.find('error').attrib.get('message','') or (case.find('error').text or '')
            elif case.find('skipped') is not None:
                status = 'skipped'
                msg = case.find('skipped').attrib.get('message','') or (case.find('skipped').text or '')
            tests_by_class[classname].append({'name':name,'time':time,'status':status,'message':msg})
    except Exception as ex:
        print('Failed to parse', path, ex)

def status_class(s):
    return 'passed' if s=='passed' else ('skipped' if s=='skipped' else 'failed')

html = []
html.append('<!doctype html>')
html.append('<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">')
html.append('<title>Surefire Report</title>')
html.append('<style>')
html.append('body{font-family:Inter,Segoe UI,Roboto,Arial,Helvetica,sans-serif;margin:16px}')
html.append('.header{display:flex;align-items:center;justify-content:space-between}')
html.append('.cards{display:flex;gap:12px;margin:12px 0}')
html.append('.card{padding:12px;border-radius:8px;background:#f7f9fb;min-width:140px}')
html.append('.card strong{display:block;font-size:18px}')
html.append('.filters{margin:12px 0}')
html.append('.class-block{border:1px solid #e6e9ee;border-radius:6px;margin-bottom:8px}')
html.append('.class-head{padding:10px;background:#fafafa;cursor:pointer;display:flex;justify-content:space-between}')
html.append('.test-row{padding:10px;border-top:1px solid #eee;display:flex;gap:12px;align-items:center}')
html.append('.test-name{flex:1}')
html.append('.status.passed{color:green}')
html.append('.status.skipped{color:orange}')
html.append('.status.failed{color:red}')
html.append('.search{padding:8px;width:320px;border:1px solid #ddd;border-radius:6px}')
html.append('.small{font-size:12px;color:#666}')
html.append('</style>')
html.append('<script>function toggle(id){var e=document.getElementById(id);e.style.display=(e.style.display=="none")?"block":"none"}function filterTests(){var q=document.getElementById("q").value.toLowerCase();var s=document.getElementById("status").value;document.querySelectorAll(".test-row").forEach(function(r){var name=r.getAttribute("data-name").toLowerCase();var cls=r.getAttribute("data-status");var ok=(q==""||name.indexOf(q)!==-1)&&(s=="all"||s==cls);r.style.display=ok?"flex":"none"})}</script>')
html.append('</head><body>')
html.append('<div class="header"><h1>Surefire Report</h1><div class="small">Generated by script</div></div>')
html.append(f'<div class="cards"><div class="card"><strong>{summary["tests"]}</strong><div class="small">Total tests</div></div><div class="card"><strong style="color:red">{summary["failures"]}</strong><div class="small">Failures</div></div><div class="card"><strong style="color:orange">{summary["skipped"]}</strong><div class="small">Skipped</div></div><div class="card"><strong>{summary["errors"]}</strong><div class="small">Errors</div></div><div class="card"><strong>{summary["time"]:.2f}s</strong><div class="small">Total time</div></div></div>')
html.append('<div class="filters"><input id="q" class="search" placeholder="Search test name or class" oninput="filterTests()"> <select id="status" onchange="filterTests()"><option value="all">All</option><option value="passed">Passed</option><option value="skipped">Skipped</option><option value="failed">Failed</option></select></div>')

idx=0
for classname, cases in sorted(tests_by_class.items()):
    cid = f'class_{idx}'
    passed = sum(1 for c in cases if c['status']=='passed')
    failed = sum(1 for c in cases if c['status'] in ('failure','error'))
    skipped = sum(1 for c in cases if c['status']=='skipped')
    html.append(f'<div class="class-block">')
    html.append(f'<div class="class-head" onclick="toggle("+"\'"+cid+"\'"+")">')
    html.append(f'<div><strong>{escape(classname)}</strong><div class="small">{len(cases)} tests — <span style="color:green">{passed} passed</span> <span style="color:red">{failed} failed</span> <span style="color:orange">{skipped} skipped</span></div></div>')
    html.append(f'<div class="small">click to expand</div>')
    html.append('</div>')
    html.append(f'<div id="{cid}" style="display:block">')
    for c in cases:
        st = 'passed' if c['status']=='passed' else ('skipped' if c['status']=='skipped' else 'failed')
        html.append(f'<div class="test-row" data-name="{escape(c["name"])}" data-status="{st}">')
        html.append(f'<div class="test-name">{escape(c["name"])}</div>')
        html.append(f'<div class="small">{escape(str(c["time"]))}s</div>')
        html.append(f'<div class="status {st}">{escape(st)}</div>')
        html.append(f'<div class="small">{escape(c["message"] or "")}</div>')
        html.append('</div>')
    html.append('</div></div>')
    idx += 1

html.append('</body></html>')

with open(OUT_FILE, 'w', encoding='utf-8') as f:
    f.write('\n'.join(html))

print('Wrote', OUT_FILE)
